# -*- coding: utf-8 -*-
"""Data-Types-in-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZhWJhul0FfPyP5e5zwtXvl9R3TnsPHQ
"""

# Data Types In Python
# types of Data types
  # 1. Primitive
  # 2. non-primitive

"""Python Data Types:

**Primitive Data Types:**

*   **Integer (`int`):** Whole numbers (e.g., `5`, `-100`).
*   **Float (`float`):** Numbers with decimal points (e.g., `3.14`, `-0.5`).
*   **String (`str`):** Sequences of characters (e.g., `"hello"`, `"Python"`).
*   **Boolean (`bool`):** Represents truth values (`True` or `False`).

**Non-Primitive Data Types:**

*   **List (`list`):** Ordered, mutable collections of items (e.g., `[1, 2, 3]`, `["apple", "banana"]`).
*   **Tuple (`tuple`):** Ordered, immutable collections of items (e.g., `(1, 2, 3)`, `("red", "blue")`).
*   **Set (`set`):** Unordered collections of unique items (e.g., `{1, 2, 3}`, `{"a", "b", "c"}`).
*   **Dictionary (`dict`):** Unordered collections of key-value pairs (e.g., `{"name": "John", "age": 30}`).
"""

# Primitive Data types
# int -
# count = 12
# print(count)
# type(count)


# float -
# num = 125.00
# print(num)
# type(num)


# string -
# str1 = "Python Tutorial"
# print(str1)
# type(str1)


# Boolean -
# bool_var = False
# print(bool_var)
# type(bool_var)

# non-primitive -

# ---> list - mutable
# - is a arrangement of data or technically we can say that it is a well-defined collection of similar or different data elements
# - denoted by "[ele1, ele2, ele3, ......]" and each & every elements are separated by ","
# - here in list, each and every element has it's unique identity which is known as index value
# - index value will start it's value from 0 and goes upto the length of the list
# - indexing - procedure in which we will accessing our value of list through index values
# if you want to update any element in a list then you've to update them

# li = [] # empty list
# print(li)
# type(li)

# li = [10,20,30,50,60]
# li = [10,"Ankur Warikoo",3.02,True]
# type(li)
# print("before updating", li)
# type(li)
# len(li)

# print(li[0])
# print(li[1])
# print(li[2])
# print(li[3])
# print(li[4])


# updating a list -
# li[3] = 25
# print("after updating", li)
# li[0] = 11
# li




# method - it will perform some operations on which entity - list, tuple, set, dictionary


# [] - list
# () - tuple
# {} - set & dictionary

# -> case sensitive - jo chiz jis tarah se banai gyi hai usse ussi tarah use karna hoga!

# ---> tuple - immutable
# - is also a well-defined collection of the similar data and different data elements
# - denoted by "()" and each and every elements are separated by ","
# - here in tuple, each and every element has it's unique identity which is known as index value
# - tuple is immutable that means we can't change any element in tuple using indexes


# immutable - enitity can't be changed
# mutable   - enitity can be changed


# tup = ()
# print(tup)
# type(tup)


# tup = (10,20,30,50,90,650)
# print(tup)
# type(tup)

# mixed_tup = (10,"20",3.0,True,90,650)
# print(mixed_tup)
# type(mixed_tup)


# indexing in tuple -
# mixed_tup[0] = "Bhavesh"




# ---> set
# - it is also a well-defined collection of data (same or differ both)
# - set is not structured! it is non-structured
# - coz of it's unstructured behaviour set doesn't contains index values
# - it will store a data in single unit

# set_1 = {10,True,30,"50",90,650}
# print(set_1)
# print(set_1[0]) # we can't access any element in set using indexing
# type(set_1)




# ---> Dictionary - is also a well-defined collection of (same and differ both data) but in the format of key & value pair

# jaadu = {
#     "key": "value"
# }
# set_1 = {10,20,30,60}
# print(type(jaadu))
# print(type(set_1))

# prod_details = {
#     "mechanical keyboard" : ["Kreo Keyboard", "TVS Keyboard"]
# }



# Tata - employees Data

# empDetails = {
#     "empName": "Rahul Prajapati",
#     "empAge": 65,
#     "empSalary": 120000.0002,
#     "empStatus": True,
#     "empFavMov": ["Captain America", "Thor", "Piku", "Loki"]
# }

# print(empDetails['empStatus'])
# print(empDetails['empAge'])
# print(empDetails['empSalary'])
# empDetails['empName'] = "Arshad"
# empDetails['empAge'] = 25
# empDetails
# empDetails['empFavMov']
# type(empDetails)

# tomorrow