# -*- coding: utf-8 -*-
"""Conditional Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KOzfOMXB-0Xq7qRCMyeGrNTkTv3sPfxk
"""

# Conditional Statements - are those kind of statement through which
# we can operate or evaluate certain task or operation on the behalf of certain conditions
# we have to use -
# 1. if
# 2. else
# 3. elif

# indentation - agar ek zone ke andar aapne sahi code nahi likha to usme kya aayegi Indentation error

# day = "Tuesday"

# if(day == "Monday"):
#   print("Working Day!")
# if(day == "Tuesday"):
#   print("Working Day!")
# if(day == "Wednesday"):
#   print("Working Day!")
# if(day == "Thursday"):
#   print("Working Day!")
# if(day == "Friday"):
#   print("Working Day!")

# if(day == "Saturday"):
#   print("Working Day!")
# else:
#   print("Holiday!")

# that's why python community comes with a new keyword, i.e. "elif"

day = "feb"

if(day == "Monday"):
  print("Monday Working Day!")
elif(day == "Tuesday"):
  print("Tuesday Working Day!")
elif(day == "Wednesday"):
  print("Wednesday Working Day!")
elif(day == "Thursday"):
  print("Thursday Working Day!")
elif(day == "Friday"):
  print("Friday Working Day!")
elif(day == "Saturday"):
  print("Saturday Working Day!")
else:
  print("Holiday!")

