# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZhWJhul0FfPyP5e5zwtXvl9R3TnsPHQ
"""

# Python Basics Concepts -
# 1. Variables in Python
# 2. Data-Types in Python
# 3. Operators in Python
# 4. Conditional Statements
# 5. Control-Flow Statement
# 6. Functions
        # - built-in function
        # - user-defined function
# 7. Ad. functions - Lambda function




# NumPy Concepts - Numerical Python




# Pandas Concepts - Categorized Data

# Variables in Python - are like container where we will store our data | value

# count = 53
# print(count) # for vs code users
# count


# Criterias to declare a variable in python -
# - numerical character should not be at the starting of the variable name
# - we can include alphabetical characters, alpha-num characters but we can't include num-alpha chars
# - we can't use any special character like (@, #, $, %, ^, &, *, (), [], {}, -, +, /, .......etc) except "_"


# _num_1 = 10
# _num_1

