# -*- coding: utf-8 -*-
"""Operators-in-Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZhWJhul0FfPyP5e5zwtXvl9R3TnsPHQ
"""

# Operators - the symbols which we can use to perform certain task or operation is known as operators
# Operand   - are the enitity on which we will apply or perform operations
# Operation - A Procedure in which certain task is performed


# Types of Operators -
# 1. Airthmatic Operators - +, -, *, /, **, //, %
# 2. Assignment Operators - =, +=, -=, *=, /=, **=, //=, %=
# 3. Comparison Operators - ==, !=, >, <, >=, <=
# 4. Logical Operators    - and, or, not
# 5. Membership Operators -
# 6. Identity Operators   -
# 7. Bit-wise Operators   -

# 1. Airthmatic Operators - +, -, *, /, **, //, %

# + :
num1 = 10
num2 = 65

total_sum = num1 + num2
print("the sum is : ", total_sum)


# - :
num1 = 10
num2 = 65

total_sub = num1 - num2
print("the subtraction is : ", total_sub)


# / :
num1 = 10
num2 = 65

total_div = num1 / num2
print("the division is : ", total_div)


# * :
num1 = 6
num2 = 15

total_mul = num1 * num2
print("the multiplication is : ", total_mul)


# // : floor division
num1 = 10
num2 = 65

total_div = num2 // num1
print("the floor division is : ", total_div)


# ** : exponential
num1 = 2
num2 = 65

total_div = num2 ** num1
print("the exponential(power) is : ", total_div)


# % : modulus
num1 = 64
num2 = 65

total_div = num1 % num2
print("the modulus(remainder) is : ", total_div)

# 2. Assignment Operators - =, +=, -=, *=, /=, **=, //=, %=
num3 = 29
num4 = 52

num3 += num4             # num3 += num4    --->    num3 = num3 + num4     --->        num3 = 29 + 52      --->     num3 = 81
print(num3)

num3 -= num4             # num3 -= num4    --->    num3 = num3 - num4     --->        num3 = 81 - 52      --->     num3 = 31
print(num3)

num4 *= num3             # num4 *= num3    --->    num4 = num4 * num3     --->        num4 = 52 * 31      --->     num4 = 1612
print(num4)

num4 /= num3             # num4 /= num3    --->    num4 = num4 / num3     --->        num4 = 1612 / 31      --->     num4 = 52
print(num4)

num3 = 2
num4 = 52
num4 **= num3             # num4 **= num3    --->    num4 = num4 ** num3     --->        num4 = 52 ** 2      --->     num4 = 2704
print(num4)


num4 = 25689
num3 = 13
num4 //= num3             # num4 //= num3    --->    num4 = num4 // num3     --->        num4 = 25689 // 13      --->     num4 = 1976
print(num4)
num4 /= num3             # num4 /= num3    --->    num4 = num4 / num3     --->        num4 = 25689 / 13      --->     num4 = 1976.
print(num4)


num4 %= num3             # num4 %= num3    --->    num4 = num4 % num3     --->        num4 = 1976.0........ % 13      --->     num4 = 9
print(num4)

# 3. Comparison Operators - ==, !=, >, <, >=, <=
# it will always return a boolean value

num5 = 56
num6 = 13

print(num5 == num6)     # False


num5 = 78
num6 = 78
print(num5 == num6)     # True (int == int)       False (int == str)



print(num5 != num6)     # True
print(num5 > num6)      # True
print(num5 < num6)      # False
print(num5 >= num6)     # True
print(num5 <= num6)     # False

# Logical Operators - and | or | not   -   whenver you've to perform some task on the basis of certain conditions, you use comparison operators
# - but if we want to perform some task on the basis of more than a condition then you must use logical operator

count1 = 10
count2 = 20
count3 = 30
print(count1)
print(count2)
print(count3)

print("------------ and logical opr -------------")

print(count1 < count2 and count1 < count3)
print(count2 < count1 and count2 < count3)
print(count3 < count2 and count3 < count1)

print("------------ or logical opr ------------")

print(count1 < count2 or count1 < count3)
print(count2 < count1 or count2 < count3)
print(count3 < count2 or count3 < count1)




print("------------ not (and) ------------")

print(not(count1 < count2 and count1 < count3))
print(not(count2 < count1 and count2 < count3))
print(not(count3 < count2 and count3 < count1))

print("------------ not (or) ------------")

print(not(count1 < count2 or count1 < count3))
print(not(count2 < count1 or count2 < count3))
print(not(count3 < count2 or count3 < count1))

